cc_test(
    name = "cache_test",
    srcs = [
        "cache_test.cc"
    ],
    size = "small"
)

cc_test(
    name = "with_deps_test",
    srcs = ["with_deps_test.cc"],
    size = "small",
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        ]
)